version: '2'
services:
  ifyum-postgres:
    image: postgres:latest
#    ultima version usar
#    image: postgres:latest
    # volumes:
    #     - ~/volumes/jhipster/ifyummysql/mysql/:/var/lib/mysql/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
#
  